name: Gatsby Publish

on:
  push:
    branches:
      - master-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Github Pages Custom Deploy
        uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.PAT }}
          source-directory: public
          build-command: npm run deploy
          deploy-branch: master-dev
