name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: srepollock/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.PAT }}
          skip-publish: true
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          folder: public

